### ISSUE TITLE
docker-compose upでttyをつけているのにプロセスが終了する。

### ISSUE THREAD

**Issue by takerumimata** [Koshizuka-lab/takerumimata-face-auth#8]
## Dockerによる仮想化
#4 

## compose upでプロセスが終了する

dockerfile
```
FROM python:3.6

# opencv-devのインストール
RUN apt-get update -y && apt-get install -y libopencv-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TensorflowとOpencvのインストール
RUN pip3 install numpy tensorflow opencv-python

ENV APP_NAME tensor-docker
WORKDIR /home/$APP_NAME

CMD [ '/bin/bash'  ]
```
ビルドを行ったらbashを起動する

docker-compose.yml
```
version: '3'
services:
  web:
    build: .
    tty: true
    volumes:
      - ./python:/home/tensor-docker
```

ttyをつけているので起動したままになってくれるはずなのだが、そうはならない
```
$ docker-compose up
Recreating takerumimata-face-auth_web_1 ... done
Attaching to takerumimata-face-auth_web_1
takerumimata-face-auth_web_1 exited with code 0
```

**Comment by takerumimata** [comment]
docker-composeファイルにてコマンドを指定することで解決した

```
version: '3'
services:
  web:
    build: .
    volumes:
      - ./python:/home/tensor-docker
    tty: true
    stdin_open: true
    command: ["/bin/bash"]

```

なぜDockerfileのコマンドは終了するのかは謎
